# # Use the official Python image from the Docker Hub
# FROM python:3.12-slim
 
# # Set the working directory in the container
# WORKDIR /app
 
# # Copy the requirements file to the working directory
# COPY requirements.txt .
 
# # Install any needed packages specified in requirements.txt
# RUN pip install -r requirements.txt
 
# # Copy the rest of the application code to the working directory
# COPY . .
 
# # Make port 5000 available to the world outside this container
# EXPOSE 5000
 
# # Define environment variable for Flask
# ENV FLASK_APP=app.py
 
# # Run the application
# CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
 
 
 
# Use the official Python image from the Docker Hub
FROM python:3.12-slim
 
# Set the working directory in the container
WORKDIR /app
 

# Copy the requirements file to the working directory
COPY requirements.txt .
 
# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
 
# Copy the rest of the application code to the working directory
COPY . .
 
# Make port 5000 available to the world outside this container
EXPOSE 5000
 
# Define environment variable for Flask
ENV FLASK_APP=app.py
 
# Run the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]